import { Annotation } from "@langchain/langgraph";
import { Analysis } from "../types/analysis";
import { Reflection } from "../types/reflection";
import { ResearchDocument } from "../types/document";
import { SearchHistory } from "../types/searchHistory";

export const ResearchState = Annotation.Root({
  // Original user query
  query: Annotation<string>(),

  // Initial plan generated by the planner
  plan: Annotation<string[]>(),

  // Retrieved documents from all sources
  documents: Annotation<ResearchDocument[]>({
    reducer: (curr, update) => [...curr, ...update],
    default: () => [],
  }),

  // History of every retrieval performed
  searchHistory: Annotation<SearchHistory[]>({
    reducer: (curr, update) => [...curr, ...update],
    default: () => [],
  }),

  // Current analysis
  analysis: Annotation<Analysis>(),

  // Reflection output
  reflection: Annotation<Reflection>(),

  // Number of retrieval iterations completed
  iteration: Annotation<number>({
    value: (_, update) => update,
    default: () => 0,
  }),

  // Final report
  report: Annotation<string>(),
});
