import { Annotation } from "@langchain/langgraph";
import { Analysis } from "../types/analysis";
import { Reflection } from "../types/reflection";
import { ResearchDocument } from "../types/document";
import { SearchHistory } from "../types/searchHistory";
import { Report } from "../types/report";

export const ResearchState = Annotation.Root({
  // Original user query
  query: Annotation<string>(),

  // Initial plan generated by the planner
  plan: Annotation<string[]>(),

  mode: Annotation<"chat" | "research">(),

  response: Annotation<string>({
    value: (_, update) => update,
    default: () => "",
  }),

  // Retrieved documents from all sources
  documents: Annotation<ResearchDocument[]>({
    reducer: (curr, update) => [...curr, ...update],
    default: () => [],
  }),

  // curr new retrived doc
  newDocuments: Annotation<ResearchDocument[]>(),

  // Current analysis
  analysis: Annotation<Analysis[]>({
    reducer: (curr, update) => [...curr, ...update],
    default: () => [],
  }),

  // History of every retrieval performed
  searchHistory: Annotation<SearchHistory[]>({
    reducer: (curr, update) => [...curr, ...update],
    default: () => [],
  }),

  // Reflection output
  reflection: Annotation<Reflection>(),

  // Number of retrieval iterations completed
  iteration: Annotation<number>({
    value: (_, update) => update,
    default: () => 0,
  }),

  // Final report
  report: Annotation<Report>(),
});
